### PR TITLE
Add git ignore file

### PR DESCRIPTION
**Pull request by talhatahir**
Add git ignore file

### CODE REVIEW

**Comment by Strike2-ux** [comment]
Thank you Tahir

**Comment by Strike2-ux** [comment]
Well if you  want a development utilities to run faster, always configure .ignore file, so your script will excecute in the right order. Time it's money.

**Comment by talhatahir** [comment]
@Strike2-ux please review it too. Thanks

**Review by yaKashif — APPROVED** [review]

**Comment by talhatahir** [comment]
@Strike2-ux please approve the Pull request so it can be merged. thanks

**Pull request merged**
